apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-service
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/nexticket-production/event-service:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        - name: FRONTEND_URL
          value: https://nexticket-delta.vercel.app
        - name: PORT
          value: '8080'
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        # CRITICAL: Startup probe with longer timeout
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 12  # 12 * 10s = 120s total startup time
        # Liveness probe (after startup)
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 3